export const REQUEST_SCHEDULE = 'REQUEST_SCHEDULE';
export const RECIEVE_SCHEDULE = 'RECIEVE_SCHEDULE';
export const REQUEST_GAME = 'REQUEST_GAME';
export const RECIEVE_GAME = 'RECIEVE_GAME';
export const SET_SELECTED_GAME = 'SET_SELECTED_GAME';
