module.exports = {
  FA: 'Fastball',
  FF: '4-Seam Fastball',
  FT: '2-Seam Fastball',
  FC: 'Cutter',
  FO: 'Forkball',
  FS: 'Splitter',
  SI: 'Sinker',
  SL: 'Slider',
  CU: 'Curveball',
  KC: 'Knuckle Curve',
  SC: 'Screwball',
  GY: 'Gyroball',
  CH: 'Changeup',
  KN: 'Knuckleball',
  IN: 'Int. Ball',
  PO: 'Pitchout',
  UN: 'Unknown',
  SN: 'Unknown',
  AB: 'Auto. Ball',
  AS: 'Auto. Strike',
  NP: 'No Pitch',
  EP: 'Eephus',
};
